export default {
  'common.login': 'Đăng nhập',
  'common.logout': 'Đăng kí',
  'common.back_home': 'Về Trang Chủ',
  'common.back_login': 'Quay lại trang đăng nhập',
  'common.email': 'Email',
  'common.password': 'Mật khẩu',
  'common.message.copy_success': 'Sao chép thành công',
  'common.message.request_error': 'Yêu cầu thất bại',
  'common.message.request_success': 'Yêu cầu thành công',
  'common.message.request_network_error': 'Kết nối mạng không ổn định',
  'common.message.reqeust_network_error.desc': 'Kết nối mạng bất thường,không thể kết nối đến máy chủ',
  'common.table.no_data': 'Không có dữ liệu',
  'module.dashboard': 'dashboard',
  'module.config.system': 'Cấu hình hệ thống',
  'module.config.payment': 'Cấu hình thanh toán',
  'module.server.manage': 'Quản lý máy chủ',
  'module.server.group': 'Nhóm máy chủ',
  'module.plan': 'Quản lý đăng kí',
  'module.order': 'Quản lý đơn hàng',
  'module.coupon': 'Quản lý coupon',
  'module.user': 'Quản lý người dùng',
  'module.notice': 'Quản lý thông báo',
  'module.ticket': 'Quản lý công việc',
  'module.knowledge': 'Quản lý kiến thức',
  'module.group.setting': 'Cài đặt',
  'module.group.server': 'Máy chủ',
  'module.group.billing': 'Tài chính',
  'module.group.user': 'Người dùng',
  'module.group.index': 'Chỉ số',
  'module.monitor_queue': 'Giám sát hàng đợi',
  'module.dashboard.month_income': 'Tổng thu nhập tháng này',
  'module.dashboard.last_month_income': 'Tổng thu nhập tháng trước',
  'module.dashboard.month_register_total': 'Người dùng mới tháng này',
  'module.dashboard.ticket_pendding_total': 'Tổng số ticket chưa xử lý',
  'module.dashboard.commission_pending_tota': 'Hoa hồng chưa xác nhận',
  'module.dashboard.server_last_rank': 'Xếp hạng lưu lượng máy chủ hôm qua',
  'module.dashboard.monitor_stats.warning': 'Hàng đợi đang gặp sự cố,có thể gây ảnh hưởng đến kinh doanh',
  'module.config.system.message.sava_success': 'Lưu thành công',
  'module.config.system.site': 'Trang web',
  'module.config.system.site.app_name': 'Tên trang web',
  'module.config.system.site.app_name.tip': 'Sử dụng để hiển thị tên trang web khi cần thiết.',
  'module.config.system.site.app_name.placeholder': 'Nhập tên trang web',
  'module.config.system.site.app_description': 'Mô tả trang web',
  'module.config.system.site.app_description.tip': 'Sử dụng để hiển thị mô tả trang web khi cần thiết.',
  'module.config.system.site.app_description.placeholder': 'Nhập mô tả trang web',
  'module.config.system.site.app_url': 'URL trang web',
  'module.config.system.site.app_url.tip': 'Hệ thống sẽ sử dụng URL này khi cần cung cấp URL cho bên ngoài, ví dụ: thanh toán, email, thông báo, v.v.',
  'module.config.system.site.app_url.placeholder': 'Nhập URL trang web, không sử dụng dấu gạch chéo cuối cùng',
  'module.config.system.site.subscribe_url': 'URL Đăng ký',
  'module.config.system.site.subscribe_url.tip': 'Sử dụng cho việc đăng ký, để trống nếu muốn sử dụng URL trang web. Trong trường hợp muốn đùng nhiều URL và ngẫu nhiên,sử dụng dấu phẩy để phân tách',
  'module.config.system.site.subscribe_url.placeholder': 'Nhập URL đăng ký, không sử dụng dấu gạch chéo cuối cùng. Sử dụng dấu phẩy để phân tách trong trường hợp có nhiều tên miền',
  'module.config.system.site.tos_url': 'URL Điều khoản Sử dụng (TOS) Người dùng',
  'module.config.system.site.tos_url.tip': 'Sử dụng để chuyển hướng đến Điều khoản Sử dụng (TOS) của người dùng.',
  'module.config.system.site.tos_url.placeholder': 'Nhập URL Điều khoản Sử dụng, không có dấu gạch chéo cuối cùng',
  'module.config.system.site.safe_mode_enable': 'Chế độ Bảo mật',
  'module.config.system.site.safe_mode_enable.tip': 'Khi bật, chỉ có URL trang web này được phép truy cập từ các tên miền đã liên kết với trang web này; mọi yêu cầu từ các tên miền khác sẽ bị từ chối (HTTP 403).',
  'module.config.system.site.stop_register': 'Dừng đăng ký người dùng mới',
  'module.config.system.site.stop_register.tip': 'Khi bật, không ai có thể đăng ký người dùng mới.',
  'module.config.system.site.email_verify': 'Xác minh email',
  'module.config.system.site.email_verify.tip': 'Khi bật, người dùng sẽ bắt buộc phải xác minh email của họ.',
  'module.config.system.site.email_gmail_limit_enable': 'Hạn chế sử dụng Gmail alias',
  'module.config.system.site.email_gmail_limit_enable.tip': 'Khi bật, không cho phép đăng ký bằng Gmail alias.',
  'module.config.system.site.try_out_plan_id': 'Gói đăng ký thử nghiệm',
  'module.config.system.site.try_out_plan_id.tip': 'Chọn gói đăng ký thử nghiệm, nếu không có tùy chọn nào, vui lòng trước tiên thêm gói đăng ký trong quản lý đăng ký.',
  'module.config.system.site.try_out_plan_id.tip.placeholder': 'Chọn gói đăng ký thử nghiệm',
  'module.config.system.site.try_out_plan_id.close': 'Đóng',
  'module.config.system.site.email_whitelist_enable': 'Danh sách email thuộc whitelist được cho phép',
  'module.config.system.site.email_whitelist_enable.tip':
    'Khi bật, chỉ cho phép đăng ký với các hậu tố email có trong whitelist.',
  'module.config.system.site.email_whitelist': 'Danh sách email thuộc whitelist',
  'module.config.system.site.email_whitelist.tip': 'Sử dụng dấu phẩy để phân tách，ví dụ：qq.com,gmail.com。',
  'module.config.system.site.email_whitelist.placeholder': 'Nhập hậu tố tên miền, phân tách bằng dấu phẩy, ví dụ: qq.com, gmail.com',
  'module.config.system.site.recaptcha_enable': 'Bảo vệ chống các chương trình tự động (bot)',
  'module.config.system.site.recaptcha_enable.tip': 'Khi bật, sẽ sử dụng Google reCAPTCHA để ngăn chặn các chương trình tự động (bot).',
  'module.config.system.site.recaptcha_key': 'Khóa bí mật reCAPTCHA',
  'module.config.system.site.recaptcha_key.tip': 'Khóa bí mật được cấp từ Google reCAPTCHA.',
  'module.config.system.site.recaptcha_key.placeholder': 'Nhập',
  'module.config.system.site.recaptcha_site_key': 'Khóa trang web reCAPTCHA',
  'module.config.system.site.recaptcha_site_key.tip': 'Khóa trang web được cấp từ Google reCAPTCHA.',
  'module.config.system.site.recaptcha_site_key.placeholder': 'Nhập',
  'module.config.system.subscribe': 'Đăng ký',
  'module.config.system.subscribe.plan_change_enable': 'Cho phép người dùng thay đổi gói đăng ký',
  'module.config.system.subscribe.plan_change_enable.tip': 'Khi bật, người dùng có thể thay đổi gói đăng ký của họ.',
  'module.config.system.subscribe.reset_traffic_method': 'Phương thức đặt lại lưu lượng mỗi tháng',
  'module.config.system.subscribe.reset_traffic_method.tip': 'Phương thức đặt lại lưu lượng của người dùng, mặc định vào ngày đầu tiên của tháng',
  'module.config.system.subscribe.reset_traffic_method.placeholder': 'Chọn phương thức đặt lại gói đăng ký',
  'module.config.system.subscribe.reset_traffic_method.option.first_day': 'Ngày đầu tiên của tháng',
  'module.config.system.subscribe.reset_traffic_method.option.order_date': 'Ngày đặt hàng',
  'module.config.system.subscribe.surplus_enable': 'Kích hoạt chương trình giảm giá',
  'module.config.system.subscribe.surplus_enable.tip': 'Khi bật, khi người dùng thay đổi gói đăng ký, hệ thống sẽ tính toán giảm giá cho gói đăng ký hiện có theo hướng dẫn.',
  'module.config.system.subscribe.new_order_event_id': 'Khi có đơn hàng đăng ký mới, kích hoạt sự kiện',
  'module.config.system.subscribe.new_order_event_id.tip': 'Khi có đơn hàng đăng ký mới, sự kiện sẽ được kích hoạt khi việc đăng ký hoàn thành.',
  'module.config.system.subscribe.new_order_event_id.placeholder': 'Chọn sự kiện',
  'module.config.system.subscribe.new_order_event_id.option.do_nothing': 'Không thực hiện thao tác nào',
  'module.config.system.subscribe.new_order_event_id.option.reset_traffic': 'Đặt lại lưu lượng của người dùng',
  'module.config.system.subscribe.renew_order_event_id': 'Khi có đơn hàng đăng ký gia hạn, kích hoạt sự kiện',
  'module.config.system.subscribe.renew_order_event_id.tip': 'Khi có đơn hàng đăng ký gia hạn, sự kiện sẽ được kích hoạt khi việc gia hạn đăng ký hoàn thành.',
  'module.config.system.subscribe.renew_order_event_id.placeholder': 'Chọn sự kiện',
  'module.config.system.subscribe.renew_order_event_id.option.do_nothing': 'Không thực hiện thao tác nào',
  'module.config.system.subscribe.renew_order_event_id.option.reset_traffic': 'Đặt lại lưu lượng của người dùng',
  'module.config.system.subscribe.change_order_event_id': 'Khi có sự thay đổi trong đơn đăng ký, kích hoạt sự kiện',
  'module.config.system.subscribe.change_order_event_id.tip': 'Khi có sự thay đổi trong đơn đăng ký, sự kiện sẽ được kích hoạt khi việc thay đổi đăng ký hoàn thành.',
  'module.config.system.subscribe.change_order_event_id.placeholder': 'Chọn sự kiện',
  'module.config.system.subscribe.change_order_event_id.option.do_nothing': 'Không thực hiện thao tác nào',
  'module.config.system.subscribe.change_order_event_id.option.reset_traffic': 'Đặt lại lưu lượng của người dùng',
  'module.config.system.invite': 'Mời và Hoa hồng',
  'module.config.system.invite.invite_force': 'Kích hoạt bắt buộc Mời',
  'module.config.system.invite.invite_force.tip': 'Khi bật, chỉ những người dùng được mời mới có thể đăng ký.',
  'module.config.system.invite.invite_commission': 'Phần trăm hoa hồng',
  'module.config.system.invite.invite_commission.tip': 'Phần trăm phân chia hoa hồng mặc định, bạn có thể tùy chỉnh riêng cho từng người dùng trong quản lý người dùng.',
  'module.config.system.invite.invite_commission.placeholder': 'Nhập',
  'module.config.system.invite.invite_gen_limit': 'Giới hạn số lần tạo mã mời cho người dùng',
  'module.config.system.invite.invite_gen_limit.placeholder': 'Nhập',
  'module.config.system.invite.invite_never_expire': 'Mã mời không bao giờ hết hạn',
  'module.config.system.invite.invite_never_expire.tip': 'Khi bật, mã mời sẽ không bao giờ hết hạn sau khi được sử dụng. Nếu tắt, mã mời sẽ hết hạn sau khi được sử dụng.',
  'module.config.system.invite.commission_first_time_enable': 'Hoa hồng chỉ được trả lần đầu',
  'module.config.system.invite.commission_first_time_enable.tip': 'Khi bật, hoa hồng chỉ sẽ được trả khi người được mời thực hiện thanh toán lần đầu. Bạn có thể tùy chỉnh riêng cho từng người dùng trong quản lý người dùng.',
  'module.config.system.invite.commission_auto_check_enable': 'Xác nhận tự động hoa hồng',
  'module.config.system.invite.commission_auto_check_enable.tip': 'Khi bật, hoa hồng sẽ được tự động xác nhận sau 3 ngày kể từ khi đơn hàng hoàn thành.',
  'module.config.system.invite.commission_withdraw_limit': 'Ngưỡng yêu cầu rút tiền hoa hồng (đơn vị: VNĐ)',
  'module.config.system.invite.commission_withdraw_limit.tip': 'Các đơn hàng rút tiền hoa hồng dưới mức ngưỡng này sẽ không được gửi đơn rút tiền.',
  'module.config.system.invite.commission_withdraw_limit.placeholder': 'Nhập số',
  'module.config.system.invite.commission_withdraw_method': 'Phương thức rút tiền hoa hồng',
  'module.config.system.invite.commission_withdraw_method.tip': 'Các phương thức rút tiền hỗ trợ.',
  'module.config.system.invite.commission_withdraw_method.placeholder': 'Nhập các phương thức, phân tách bằng dấu phẩy, ví dụ: PayPal, USDT, ZaloPay',
  'module.config.system.invite.withdraw_close_enable': 'Tắt tính năng rút tiền',
  'module.config.system.invite.withdraw_close_enable.tip': 'Khi tắt, người dùng sẽ bị cấm đăng ký rút tiền, và hoa hồng từ việc mời sẽ được cộng vào tài khoản còn lại của người dùng.',
  'module.config.system.frondend': 'Giao diện trước',
  'module.config.system.frondend.warning': 'Nếu bạn triển khai V2board theo mô hình phân tách giao diện trước và giao diện sau, cấu hình trang này sẽ không có hiệu lực.',
  'module.config.system.frondend.frontend_theme': 'Giao diện người dùng',
  'module.config.system.frondend.frontend_theme.tip': 'Chọn giao diện cho phần giao diện người dùng, bạn có thể tải lên các giao diện mới vào thư mục public/theme để sử dụng.',
  'module.config.system.frondend.frontend_admin_path': 'Đường dẫn trang quản trị',
  'module.config.system.frondend.frontend_admin_path.tip': 'Đường dẫn đến trang quản trị, thay đổi đường dẫn này sẽ làm thay đổi đường dẫn admin mặc định.',
  'module.config.system.frondend.light': 'Sáng',
  'module.config.system.frondend.dark': 'Tối',
  'module.config.system.frondend.frontend_theme_sidebar': 'Kiểu thanh bên',
  'module.config.system.frondend.frontend_theme_header': 'Kiểu tiêu đề',
  'module.config.system.frondend.frontend_theme_color': 'Màu chủ đề',
  'module.config.system.frondend.frontend_theme_color.option.default': 'Mặc định',
  'module.config.system.frondend.frontend_theme_color.option.black': 'Đen',
  'module.config.system.frondend.frontend_theme_color.option.darkblue': 'Xanh đậm',
  'module.config.system.frondend.frontend_theme_color.option.green': 'Xanh lá cây',
  'module.config.system.frondend.frontend_background_url': 'Hình nền',
  'module.config.system.frondend.frontend_background_url.tip': 'Sẽ được hiển thị trên trang đăng nhập.',
  'module.config.system.frondend.frontend_customer_service_method': 'Hệ thống dịch vụ khách hàng bên thứ ba',
  'module.config.system.frondend.frontend_customer_service_method.tip': 'Chọn hệ thống dịch vụ khách hàng bên ngoài cụ thể.',
  'module.config.system.frondend.frontend_customer_service_method.option.close': 'Tắt',
  'module.config.system.frondend.frontend_customer_service_method.option.crisp': 'Crisp',
  'module.config.system.frontend.frontend_customer_service_id': 'Mã nhận dạng',
  'module.config.system.frontend.frontend_customer_service_id.tip': 'Một chuỗi ký tự được cung cấp bởi hệ thống dịch vụ khách hàng để nhận dạng bạn.',
  'module.config.system.frontend.frontend_customer_service_id.placeholder': 'Nhập',
  'module.config.system.server': 'Máy chủ',
  'module.config.system.server.server_token': 'Khóa truyền thông',
  'module.config.system.server.server_token.tip': 'Khóa truyền thông giữa V2board và máy chủ, đảm bảo dữ liệu không bị truy cập bởi người khác.',
  'module.config.system.server.server_token.placeholder': 'Nhập',
  'module.config.system.server.server_license': 'Tệp giấy phép',
  'module.config.system.server.server_license.tip': 'Nếu máy chủ bạn đang sử dụng yêu cầu tệp giấy phép, bạn có thể điền vào đây.',
  'module.config.system.server.server_license.placeholder': 'Nhập',
  'module.config.system.server.server_log_enable': 'Ghi nhật ký',
  'module.config.system.server.server_log_enable.tip': 'Có ghi nhật ký cho máy chủ hay không, tắt có thể giúp tránh lượng dữ liệu nhật ký quá lớn trên đĩa.',
  'module.config.system.server.server_v2ray_domain': 'Bộ lọc tên miền toàn cầu V2ray',
  'module.config.system.server.server_v2ray_domain.tip': 'Các quy tắc ở đây sẽ được kết hợp với các quy tắc được cấu hình trên các nút để thực hiện việc lọc, mỗi dòng một quy tắc.',
  'module.config.system.server.server_v2ray_domain.placeholder': 'Nhập',
  'module.config.system.server.server_v2ray_protocol': 'Bộ lọc giao thức toàn cầu V2ray',
  'module.config.system.server.server_v2ray_protocol.tip': 'Các quy tắc ở đây sẽ được kết hợp với các quy tắc được cấu hình trên các nút để thực hiện việc lọc, mỗi dòng một quy tắc.',
  'module.config.system.server.server_v2ray_protocol.placeholder': 'Nhập',
  'module.config.system.email': 'Email',
  'module.config.system.email.warning': 'Nếu bạn thay đổi cấu hình trang này, bạn cần khởi động lại dịch vụ hàng đợi. Hơn nữa, cấu hình trang này ưu tiên hơn cấu hình email trong tệp .env.',
  'module.config.system.email.email_host': 'Địa chỉ máy chủ SMTP',
  'module.config.system.email.email_host.tip': 'Địa chỉ máy chủ được cung cấp bởi nhà cung cấp dịch vụ email.',
  'module.config.system.email.email_host.placeholder': 'Nhập',
  'module.config.system.email.email_port': 'Cổng máy chủ SMTP',
  'module.config.system.email.email_port.tip': 'Các cổng phổ biến bao gồm 25, 465, 587.',
  'module.config.system.email.email_port.placeholder': 'Nhập',
  'module.config.system.email.email_encryption': 'Phương thức mã hóa SMTP',
  'module.config.system.email.email_encryption.tip': 'Phương thức mã hóa thường là SSL cho cổng 465 và TLS cho cổng 587.',
  'module.config.system.email.email_encryption.placeholder': 'Nhập',
  'module.config.system.email.email_username': 'Tài khoản SMTP',
  'module.config.system.email.email_username.tip': 'Tài khoản được cung cấp bởi nhà cung cấp dịch vụ email.',
  'module.config.system.email.email_username.placeholder': 'Nhập',
  'module.config.system.email.email_password': 'Mật khẩu SMTP',
  'module.config.system.email.email_password.tip': 'Mật khẩu được cung cấp bởi nhà cung cấp dịch vụ email.',
  'module.config.system.email.email_password.placeholder': 'Nhập',
  'module.config.system.email.email_from_address': 'Địa chỉ gửi email',
  'module.config.system.email.email_from_address.tip': 'Địa chỉ gửi email được cung cấp bởi nhà cung cấp dịch vụ email.',
  'module.config.system.email.email_from_address.placeholder': 'Nhập',
  'module.config.system.email.email_template': 'Mẫu email',
  'module.config.system.email.email_template.tip': 'Bạn có thể xem tài liệu để biết cách tùy chỉnh mẫu email.',
  'module.config.system.email.email_template.placeholder': 'Chọn',
  'module.config.system.telegram': 'Telegram',
  'module.config.system.telegram.telegram_bot_enable': 'Bật thông báo bot',
  'module.config.system.telegram.telegram_bot_enable.tip': 'Khi bật, bot sẽ gửi thông báo cơ bản cho các quản trị viên và người dùng đã liên kết với Telegram.',
  'module.config.system.telegram.telegram_bot_token': 'Mã thông báo bot',
  'module.config.system.telegram.telegram_bot_token.tip': 'Nhập mã thông báo do Botfather cung cấp.',
  'module.config.system.telegram.telegram_set_webhook': 'Thiết lập Webhook',
  'module.config.system.telegram.telegram_set_webhook.tip': 'Thiết lập Webhook cho bot, nếu không thiết lập, bạn sẽ không nhận được thông báo Telegram.',
  'module.config.system.telegram.telegram_set_webhook.btn': 'Thiết lập tức thì',
  'module.config.system.telegram.telegram_set_webhook.message.success': 'Thiết lập Webhook thành công',
  'module.config.system.app': 'Ứng dụng',
  'module.config.system.app.warning': 'Quản lý phiên bản và cập nhật cho ứng dụng của bạn',
  'module.config.system.app.windows_version': 'Phiên bản Windows',
  'module.config.system.app.windows_version.tip': 'Số phiên bản và địa chỉ tải xuống cho phiên bản Windows.',
  'module.config.system.app.macos_version': 'Phiên bản MacOS',
  'module.config.system.app.macos_version.tip': 'Số phiên bản và địa chỉ tải xuống cho phiên bản MacOS.',
  'module.config.system.app.android_version': 'Phiên bản Android',
  'module.config.system.app.android_version.tip': 'Số phiên bản và địa chỉ tải xuống cho phiên bản Android.',
  'module.config.payment.add_btn': 'Thêm phương thức thanh toán',
  'module.config.payment.list.column.id': 'ID',
  'module.config.payment.list.column.enable': 'Bật',
  'module.config.payment.list.column.name': 'Tên hiển thị',
  'module.config.payment.list.column.payment': 'Giao diện thanh toán',
  'module.config.payment.list.column.notify_url': 'URL Thông báo',
  'module.config.payment.list.column.notify_url.tip': 'Cổng thanh toán sẽ thông báo dữ liệu đến địa chỉ này, vui lòng cho phép thông qua tường lửa.',
  'module.config.payment.list.column.action': 'Hành động',
  'module.config.payment.list.column.action.edit': 'Chỉnh sửa',
  'module.config.payment.list.column.action.drop': 'Xóa',
  'module.config.payment.list.column.action.drop.message.success': 'Xóa thành công',
  'module.config.payment.list.modal.name': 'Tên hiển thị',
  'module.config.payment.list.modal.name.placeholder': 'Sử dụng cho hiển thị giao diện',
  'module.config.payment.list.modal.payment': 'Tệp giao diện',
  'module.config.payment.list.modal.payment.placeholder': 'Chọn',
  'module.config.payment.list.edit.modal.title': 'Chỉnh sửa phương thức thanh toán',
  'module.config.payment.list.edit.message.success': 'Lưu thành công',
  'module.config.payment.list.add.modal.title': 'Thêm phương thức thanh toán',
  'module.config.payment.list.add.modal.ok_btn': 'Thêm',
  'module.config.payment.list.add.modal.cancel_btn': 'Hủy',
  'module.config.payment.list.add.message.success': 'Thêm thành công',
  'module.server.manage.search.placeholder': 'Tìm kiếm',
  'module.server.manage.save_sort_btn': 'Lưu sắp xếp',
  'module.server.manage.save_sort.message.success': 'Lưu sắp xếp thành công',
  'module.server.manage.list.column.action': 'Hành động',
  'module.server.manage.list.column.action.drop': 'Xóa',
  'module.server.manage.list.column.action.drop.message.success': 'Xóa thành công',
  'module.server.manage.list.column.action.copy.message.success': 'Sao chép thành công',
  'module.server.manage.list.column.action.edit': 'Chỉnh sửa',
  'module.server.manage.list.column.action.copy': 'Sao chép',
  'module.server.manage.list.column.action.btn': 'Hành động',
  'module.server.manage.list.column.id': 'ID của Node',
  'module.server.manage.list.column.show': 'Hiển thị',
  'module.server.manage.list.column.name': 'Node',
  'module.server.manage.list.column.name.tip.error': 'Không hoạt động',
  'module.server.manage.list.column.name.tip.warning': 'Không có người sử dụng hoặc báo cáo lỗi từ máy chủ',
  'module.server.manage.list.column.name.tip.processing': 'Bình thường',
  'module.server.manage.list.columnress': 'Địa chỉ',
  'module.server.manage.list.column.online': 'Người trực tuyến',
  'module.server.manage.list.column.online.tip': 'Dựa trên tần suất báo cáo từ máy chủ',
  'module.server.manage.list.column.rate': 'Hệ số',
  'module.server.manage.list.column.rate.tip': 'Dữ liệu sử dụng sẽ được nhân với hệ số để khấu trừ',
  'module.server.manage.list.column.group': 'Nhóm quyền',
  'common.modal.group.create_title': 'Tạo nhóm',
  'common.modal.group.edit_title': 'Chỉnh sửa nhóm',
  'common.modal.group.name': 'Tên nhóm',
  'common.modal.group.name.placeholder': 'Nhập tên nhóm',
  'common.modal.group.message.create_success': 'Tạo thành công',
  'common.modal.group.message.edit_success': 'Chỉnh sửa thành công',
  'common.message.create_success': 'Tạo thành công',
  'common.message.edit_success': 'Chỉnh sửa thành công',
  'module.server.manage.drawer.add_title': 'Node mới',
  'module.server.manage.drawer.edit_title': 'Chỉnh sửa Node',
  'module.server.manage.drawer.ok_btn': 'Gửi',
  'module.server.manage.drawer.cancel_btn': 'Hủy',
  'module.server.manage.name': 'Tên Node',
  'module.server.manage.name.placeholder': 'Nhập tên Node',
  'module.server.manage.rate': 'Hệ số',
  'module.server.manage.tags': 'Nhãn Node',
  'module.server.manage.tags.placeholder': 'Nhập và nhấn Enter để thêm nhãn',
  'module.server.manage.group_id': 'Nhóm quyền',
  'module.server.manage.group_id.btn': 'Thêm nhóm quyền',
  'module.server.manage.group_id.placeholder': 'Chọn nhóm quyền',
  'module.server.manage.host': 'Địa chỉ Node',
  'module.server.manage.host.placeholder': 'Địa chỉ hoặc IP',
  'module.server.manage.port': 'Cổng kết nối',
  'module.server.manage.port.placeholder': 'Cổng kết nối cho người dùng',
  'module.server.manage.server_port': 'Cổng dịch vụ',
  'module.server.manage.server_port.placeholder': 'Cổng dịch vụ mở',
  'module.server.manage.shadowsocks.cipher': 'Thuật toán mã hóa',
  'module.server.manage.shadowsocks.cipher.placeholder': 'Chọn',
  'module.server.manage.parent_id': 'Node cha',
  'module.server.manage.parent_id.extra_link': 'Xem thêm',
  'module.server.manage.parent_id.placeholder': 'Chọn',
  'module.server.manage.parent_id.option.default': 'Không',
  'module.server.manage.trojan.allow_insecure': 'Cho phép không an toàn',
  'module.server.manage.trojan.allow_insecure.option.off': 'Không',
  'module.server.manage.trojan.allow_insecure.option.on': 'Có',
  'module.server.manage.trojan.server_name': 'SNI (Server Name Indication) của máy chủ',
  'module.server.manage.trojan.server_name.placeholder': 'Sử dụng cho xác minh chứng chỉ khi địa chỉ Node không khớp',
  'module.server.manage.v2ray.tls': 'TLS',
  'module.server.manage.v2ray.tls.tip': 'Hỗ trợ TLS yêu cầu tạo tệp /root/.server.crt và server.key trước',
  'module.server.manage.v2ray.tls.edit_btn': 'Chỉnh sửa cấu hình',
  'module.server.manage.v2ray.tls.option.off': 'Không hỗ trợ',
  'module.server.manage.v2ray.tls.option.on': 'Hỗ trợ',
  'module.server.manage.v2ray.tls_settings.drawer.title': 'Chỉnh sửa cấu hình TLS',
  'module.server.manage.v2ray.tls_settings.server_name': 'Tên máy chủ',
  'module.server.manage.v2ray.tls_settings.server_name.placeholder': 'Để trống nếu không sử dụng',
  'module.server.manage.v2ray.tls_settings.allow_insecure': 'Cho phép không an toàn',
  'module.server.manage.v2ray.server_port.placeholder': 'Cổng kết nối NAT',
  'module.server.manage.v2ray.network': 'Giao thức truyền tải',
  'module.server.manage.v2ray.network.edit_btn': 'Chỉnh sửa cấu hình',
  'module.server.manage.v2ray.network.placeholder': 'Chọn giao thức truyền tải',
  'module.server.manage.v2ray.network_settings.drawer.title': 'Chỉnh sửa cấu hình giao thức',
  'module.server.manage.v2ray.network_settings.editor.placeholder': 'Nhập cấu hình JSON ở đây',
  'module.server.manage.v2ray.rule_settings': 'Cấu hình kiểm duyệt',
  'module.server.manage.v2ray.rule_settings.tip': 'Lược đúp cần kiểm tra',
  'module.server.manage.v2ray.rule_settings.edit_btn': 'Chỉnh sửa cấu hình',
  'module.server.manage.v2ray.rule_settings.drawer.title': 'Chỉnh sửa cấu hình kiểm duyệt',
  'module.server.manage.v2ray.dns_settings': 'Cấu hình DNS',
  'module.server.manage.v2ray.dns_settings.edit_btn': 'Chỉnh sửa cấu hình DNS',
  'module.server.manage.v2ray.dns_settings.drawer.title': 'Chỉnh sửa cấu hình DNS',
  'module.server.manage.v2ray.dns_settings.domain': 'Bộ lọc tên miền',
  'module.server.manage.v2ray.dns_settings.protocol': 'Bộ lọc giao thức',
  'module.server.manage.v2ray.dns_settings.drawer.sub_title': 'Bảng máy chủ DNS',
  'module.server.manage.v2ray.dns_settings.name': 'Nhóm máy chủ',
  'module.server.manage.v2ray.dns_settings.address': 'Địa chỉ máy chủ DNS',
  'module.server.manage.v2ray.dns_settings.address.placeholder': 'Nhập địa chỉ máy chủ DNS',
  'module.server.manage.v2ray.dns_settings.port': 'Cổng',
  'module.server.manage.v2ray.dns_settings.port.placeholder': 'Cổng',
  'module.server.manage.v2ray.dns_settings.domains': 'Tên miền',
  'module.server.manage.v2ray.dns_settings.domains.placeholder':
    'Danh sách tên miền, máy chủ này sẽ được ưu tiên cho truy vấn. Một dòng một tên miền',
  'module.server.manage.v2ray.dns_settings.add_btn': 'Thêm',
  'module.server.group.add_btn': 'Thêm nhóm quyền',
  'module.server.group.list.column.id': 'ID nhóm',
  'module.server.group.list.column.name': 'Tên nhóm',
  'module.server.group.list.column.action': 'Hành động',
  'module.server.group.list.column.action.edit': 'Chỉnh sửa',
  'module.server.group.list.column.action.drop': 'Xóa',
  'module.server.group.list.column.action.drop.message.success': 'Xóa thành công',
  'module.server.group.payment.list.message.add_success': 'Thêm thành công',
  'module.server.group.payment.list.message.edit_success': 'Chỉnh sửa thành công',
  'module.notice.add_btn': 'Thêm thông báo',
  'module.notice.list.column.id': '#',
  'module.notice.list.column.title': 'Tiêu đề',
  'module.notice.list.column.created_at': 'Ngày tạo',
  'module.notice.list.column.action': 'Hành động',
  'module.notice.list.column.action.edit': 'Chỉnh sửa',
  'module.notice.list.column.action.drop': 'Xóa',
  'module.notice.modal.notice.edit_title': 'Chỉnh sửa thông báo',
  'module.notice.modal.notice.create_title': 'Tạo thông báo mới',
  'module.notice.modal.notice.title': 'Tiêu đề',
  'module.notice.modal.notice.title.placeholder': 'Nhập tiêu đề thông báo',
  'module.notice.modal.notice.content': 'Nội dung thông báo',
  'module.notice.modal.notice.content.placeholder': 'Nhập nội dung thông báo',
  'module.notice.modal.notice.img_url': 'URL hình ảnh',
  'module.notice.modal.notice.img_url.placeholder': 'Nhập URL hình ảnh',
  'module.notice.modal.notice.message.add_success': 'Thêm thành công',
  'module.notice.modal.notice.message.edit_success': 'Chỉnh sửa thành công',
  'module.notice.list.column.action.drop.message.success': 'Xóa thành công',
  'module.knowledge.add_btn': 'Thêm kiến thức',
  'module.knowledge.list.column.action': 'Hành động',
  'module.knowledge.list.column.action.btn': 'Hành động',
  'module.knowledge.list.column.action.drop': 'Xóa',
  'module.knowledge.list.column.action.drop.message.success': 'Xóa thành công',
  'module.knowledge.list.column.action.edit': 'Chỉnh sửa',
  'module.knowledge.list.column.show': 'Hiển thị',
  'module.knowledge.list.column.title': 'Tiêu đề',
  'module.knowledge.list.column.category': 'Danh mục',
  'module.knowledge.list.column.updated_at': 'Thời gian cập nhật',
  'module.knowledge.save_sort_btn': 'Lưu thứ tự',
  'module.knowledge.save_sort.message.success': 'Lưu thứ tự thành công',
  'module.knowledge.drawer.edit_title': 'Chỉnh sửa kiến thức',
  'module.knowledge.drawer.add_title': 'Thêm kiến thức',
  'module.knowledge.message.edit_success': 'Chỉnh sửa thành công',
  'module.knowledge.message.create_success': 'Tạo thành công',
  'module.knowledge.drawer.ok_btn': 'Gửi',
  'module.knowledge.drawer.cancel_btn': 'Hủy',
  'module.knowledge.title': 'Tiêu đề',
  'module.knowledge.title.placeholder': 'Nhập tiêu đề kiến thức',
  'module.knowledge.category': 'Danh mục',
  'module.knowledge.category.placeholder': 'Nhập danh mục, danh mục sẽ tự động tổ chức',
  'module.knowledge.language': 'Ngôn ngữ',
  'module.knowledge.language.placeholder': 'Chọn ngôn ngữ cho kiến thức',
  'module.knowledge.language.option.chinese': 'Tiếng Trung',
  'module.knowledge.language.option.english': 'Tiếng Anh',
  'module.knowledge.body': 'Nội dung',
  'module.plan.save_sort.message.success': 'Lưu thứ tự thành công',
  'module.plan.add_btn': 'Thêm gói đăng ký',
  'module.plan.save_sort_btn': 'Lưu thứ tự',
  'module.plan.list.column.action': 'Hành động',
  'module.plan.list.column.action.btn': 'Hành động',
  'module.plan.list.column.action.edit': 'Chỉnh sửa',
  'module.plan.list.column.action.drop': 'Xóa',
  'module.plan.list.column.action.drop.message.success': 'Xóa thành công',
  'module.plan.list.column.show': 'Tình trạng bán',
  'module.plan.list.column.renew': 'Gia hạn',
  'module.plan.list.column.name': 'Tên',
  'module.plan.list.column.count': 'Thống kê',
  'module.plan.list.column.transfer_enable': 'Băng thông',
  'module.plan.list.column.month_price': 'Hằng tháng',
  'module.plan.list.column.quarter_price': 'Hằng quý',
  'module.plan.list.column.half_year_price': 'Hằng năm',
  'module.plan.list.column.year_price': 'Hai năm',
  'module.plan.list.column.two_year_price': 'Ba năm',
  'module.plan.list.column.three_year_price': 'Thanh toán một lần',
  'module.plan.list.column.onetime_price': 'Thiết lập lại giá',
  'module.plan.list.column.group_id': 'Nhóm quyền',
  'module.plan.modal.message.edit_success': 'Chỉnh sửa thành công',
  'module.plan.modal.message.create_success': 'Tạo thành công',
  'module.plan.modal.edit_title': 'Chỉnh sửa gói đăng ký',
  'module.plan.modal.create_title': 'Tạo gói đăng ký',
  'module.plan.modal.name': 'Tên gói',
  'module.plan.modal.name.placeholder': 'Nhập tên gói',
  'module.plan.modal.content': 'Mô tả gói',
  'module.plan.modal.content.placeholder': 'Nhập mô tả gói, hỗ trợ HTML',
  'module.plan.modal.setting_price': 'Thiết lập giá',
  'module.plan.modal.setting_price.placeholder': 'Để trống nếu không muốn bán',
  'module.plan.modal.month_price': 'Hằng tháng',
  'module.plan.modal.quarter_price': 'Hằng quý',
  'module.plan.modal.half_year_price': 'Hằng năm',
  'module.plan.modal.year_price': 'Hai năm',
  'module.plan.modal.two_year_price': 'Hhai năm',
  'module.plan.modal.three_year_price': 'Ba năm',
  'module.plan.modal.onetime_price': 'Thanh toán một lần',
  'module.plan.modal.reset_price': 'Thiết lập lại gói đăng ký',
  'module.plan.modal.transfer_enable': 'Băng thông gói đăng ký',
  'module.plan.modal.transfer_enable.placeholder': 'Nhập băng thông gói đăng ký',
  'module.plan.modal.group_id': 'Nhóm quyền',
  'module.plan.modal.group_id.btn': 'Thêm nhóm quyền',
  'module.plan.modal.group_id.placeholder': 'Chọn nhóm quyền',
  'module.ticket.status.on': 'Đã mở',
  'module.ticket.status.off': 'Đã đóng',
  'module.ticket.list.column.id': '#',
  'module.ticket.list.column.subject': 'Chủ đề',
  'module.ticket.list.column.level': 'Mức độ công việc',
  'module.ticket.list.column.level.low': 'Thấp',
  'module.ticket.list.column.level.medium': 'Trung bình',
  'module.ticket.list.column.level.high': 'Cao',
  'module.ticket.list.column.reply_status': 'Tình trạng công việc',
  'module.ticket.list.column.reply_status.replied': 'Đã trả lời',
  'module.ticket.list.column.reply_status.to_be_replied': 'Chưa trả lời',
  'module.ticket.list.column.created_at': 'Thời gian tạo',
  'module.ticket.list.column.updated_at': 'Lần trả lời gần nhất',
  'module.ticket.list.column.action': 'Thao tác',
  'module.ticket.list.column.action.view': 'Xem',
  'module.ticket.list.column.action.close': 'Đóng',
  'module.ticket.message.close_success': 'Đóng thành công',
  'module.ticket.detail.user': 'Người dùng',
  'module.ticket.detail.enter_message': 'Nhập nội dung để trả lời công việc...',
  'module.user.filter_btn': 'Bộ lọc',
  'module.user.action_btn': 'Thao tác',
  'module.user.action.export_csv': 'Xuất CSV',
  'module.user.action.send_email': 'Gửi email',
  'module.user.action.batch_ban': 'Chặn nhiều',
  'module.user.list.column.action': 'Thao tác',
  'module.user.list.column.action.edit': 'Chỉnh sửa',
  'module.user.list.column.action.assign_order': 'Phân bổ đơn đặt hàng',
  'module.user.list.column.action.copy_url': 'Sao chép URL đăng ký',
  'module.user.list.column.action.reset_secret': 'Thiết lập lại UUID và URL đăng ký',
  'module.user.list.column.action.user_order': 'Đơn đặt hàng',
  'module.user.list.column.action.user_invite': 'Lời mời',
  'module.user.list.column.id': 'ID',
  'module.user.list.column.email': 'Email',
  'module.user.list.column.plan_id': 'Gói đăng ký',
  'module.user.list.column.group_id': 'Nhóm quyền',
  'module.user.list.column.t': 'Trực tuyến',
  'module.user.list.column.t.tip': 'Trạng thái trực tuyến trong nửa giờ của người dùng',
  'module.user.list.column.d': 'Đã sử dụng (G)',
  'module.user.list.column.banned': 'Trạng thái',
  'module.user.list.column.banned.off': 'Bình thường',
  'module.user.list.column.banned.on': 'Tạm dừng',
  'module.user.list.column.transfer_enable': 'Băng thông',
  'module.user.list.column.expired_at': 'Ngày hết hạn',
  'module.user.list.column.expired_at.never_expire': 'Không bao giờ hết hạn',
  'module.user.list.column.created_at': 'Ngày tham gia',
  'module.user.action.send_email.modal.title': 'Gửi email',
  'module.user.action.send_email.subject': 'Chủ đề',
  'module.user.action.send_email.subject.placeholder': 'Nhập chủ đề email',
  'module.user.action.send_email.content': 'Nội dung',
  'module.user.action.send_email.content.placeholder': 'Nhập nội dung email',
  'module.user.action.send_email.addressee': 'Người nhận',
  'module.user.action.send_email.addressee.option.all': 'Tất cả người dùng',
  'module.user.action.send_email.addressee.option.filter': 'Người dùng lọc',
  'module.user.action.send_email.message.success': 'Đã thêm vào hàng đợi thực thi',
  'module.user.action.generate.title': 'Tạo người dùng',
  'module.user.action.generate.email': 'Email',
  'module.user.action.generate.email.prefix.placeholder': 'Tài khoản (để trống để tạo hàng loạt)',
  'module.user.action.generate.email.suffix.placeholder': 'Miền',
  'module.user.action.generate.password': 'Mật khẩu',
  'module.user.action.generate.password.placeholder': 'Để trống để sử dụng mật khẩu giống với email',
  'module.user.action.generate.expired_at': 'Ngày hết hạn',
  'module.user.action.generate.expired_at.placeholder': 'Chọn ngày hết hạn cho người dùng, để trống để không giới hạn thời gian hết hạn!',
  'module.user.action.generate.plan_id': 'Kế hoạch đăng ký',
  'module.user.action.generate.plan_id.option.none': 'Không có',
  'module.user.action.generate.count': 'Số lượng tạo',
  'module.user.action.generate.count.placeholder': 'Trường hợp tạo hàng loạt, vui lòng nhập số lượng cần tạo',
  'module.user.action.generate.message.success': 'Tạo người dùng thành công',
  'module.user.action.filter.drawer.title': 'Bộ lọc',
  'module.user.action.filter.drawer.ok_btn': 'Tìm kiếm',
  'module.user.action.filter.drawer.cancel_btn': 'Hủy bỏ',
  'module.user.action.filter.drawer.reset_btn': 'Đặt lại',
  'module.user.action.filter.name': 'Điều kiện',
  'module.user.action.filter.add_btn': 'Thêm điều kiện',
  'module.user.action.filter.field_name': 'Tên trường',
  'module.user.action.filter.field_name.email': 'Email',
  'module.user.action.filter.field_name.id': 'ID người dùng',
  'module.user.action.filter.field_name.plan_id': 'Gói đăng ký',
  'module.user.action.filter.field_name.transfer_enable': 'Băng thông',
  'module.user.action.filter.field_name.d': 'Dữ liệu xuống',
  'module.user.action.filter.field_name.expired_at': 'Ngày hết hạn',
  'module.user.action.filter.field_name.uuid': 'UUID',
  'module.user.action.filter.field_name.token': 'TOKEN',
  'module.user.action.filter.field_name.banned': 'Trạng thái tài khoản',
  'module.user.action.filter.field_name.invite_by_email': 'Email người mời',
  'module.user.action.filter.field_name.invite_user_id': 'ID người mời',
  'module.user.action.filter.field_name.remarks': 'Ghi chú',
  'module.user.action.filter.condition': 'Điều kiện',
  'module.user.action.filter.condition.like': 'Mờ hình',
  'module.user.action.filter.value': 'Giá trị cần tìm',
  'module.user.action.filter.value.placeholder': 'Giá trị',
  'module.user.action.filter.value.select_placeholder': 'Vui lòng chọn giá trị',
  'module.user.action.filter.value.date_placeholder': 'Vui lòng chọn ngày',
  'module.user.action.filter.value.option.normal': 'Bình thường',
  'module.user.action.filter.value.option.banned': 'Tạm ngừng',
  'module.user.action.batch_ban.confirm.title': 'Xác nhận',
  'module.user.action.batch_ban.confirm.content': 'Bạn có chắc chắn muốn thực hiện việc tạm ngừng không?',
  'module.user.action.batch_ban.message.success': 'Tạm ngừng thành công',
  'module.user.drawer.edit.title': 'Quản lý người dùng',
  'module.user.drawer.edit.message.success': 'Chỉnh sửa thành công',
  'module.user.drawer.edit.ok_btn': 'Gửi',
  'module.user.drawer.edit.cancel_btn': 'Hủy bỏ',
  'module.user.drawer.edit.email': 'Email',
  'module.user.drawer.edit.email.placeholder': 'Nhập email',
  'module.user.drawer.edit.invite_user_id': 'ID người mời',
  'module.user.drawer.edit.invite_user_id.placeholder': 'Nhập ID người mời',
  'module.user.drawer.edit.password': 'Mật khẩu',
  'module.user.drawer.edit.password.placeholder': 'Nhập mật khẩu nếu bạn muốn thay đổi',
  'module.user.drawer.edit.balance': 'Số dư',
  'module.user.drawer.edit.balance.placeholder': 'Số dư',
  'module.user.drawer.edit.commission_balance': 'Số dư hoa hồng',
  'module.user.drawer.edit.commission_balance.placeholder': 'Số dư hoa hồng',
  'module.user.drawer.edit.u': 'Sử dụng băng thông lên',
  'module.user.drawer.edit.u.placeholder': 'Sử dụng băng thông lên',
  'module.user.drawer.edit.d': 'Sử dụng băng thông xuống',
  'module.user.drawer.edit.d.placeholder': 'Sử dụng băng thông xuống',
  'module.user.drawer.edit.transfer_enable': 'Băng thông',
  'module.user.drawer.edit.transfer_enable.placeholder': 'Nhập băng thông',
  'module.user.drawer.edit.expired_at': 'Ngày hết hạn',
  'module.user.drawer.edit.expired_at.placeholder': 'Không bao giờ hết hạn',
  'module.user.drawer.edit.plan_id': 'Gói đăng ký',
  'module.user.drawer.edit.plan_id.option.none': 'Không có',
  'module.user.drawer.edit.commission_type': 'Loại hoa hồng giới thiệu',
  'module.user.drawer.edit.commission_type.option.system': 'Theo hệ thống',
  'module.user.drawer.edit.commission_type.option.cycle': 'Hoàn tiền chu kỳ',
  'module.user.drawer.edit.commission_type.option.onetime': 'Hoàn tiền lần đầu',
  'module.user.drawer.edit.commission_rate': 'Tỷ lệ hoa hồng giới thiệu',
  'module.user.drawer.edit.commission_rate.placeholder': 'Nhập tỷ lệ hoa hồng giới thiệu (để trống nếu muốn tuân theo cài đặt của trang web)',
  'module.user.drawer.edit.discount': 'Tỷ lệ giảm giá độc quyền',
  'module.user.drawer.edit.discount.placeholder': 'Nhập tỷ lệ giảm giá độc quyền',
  'module.user.drawer.edit.discount.tip': 'Sau khi thiết lập, người dùng này sẽ luôn được hưởng tỷ lệ giảm giá này khi mua bất kỳ gói đăng ký nào',
  'module.user.drawer.edit.is_admin': 'Có là quản trị viên',
  'module.user.drawer.edit.is_staff': 'Có là nhân viên',
  'module.user.drawer.edit.remarks': 'Ghi chú',
  'module.user.drawer.edit.remarks.placeholder': 'Hãy ghi chú ở đây...',
  'module.user.drawer.edit.banned': 'Trạng thái tài khoản',
  'module.user.drawer.edit.banned.option.on': 'Tạm ngừng',
  'module.user.drawer.edit.banned.option.off': 'Bình thường',
  'common.modal.assign_order.modal.title': 'Phân phát đơn hàng',
  'common.modal.assign_order.message.success': 'Phân phát đơn hàng thành công',
  'common.modal.assign_order.email': 'Email người dùng',
  'common.modal.assign_order.plan_id': 'Chọn gói đăng ký',
  'common.modal.assign_order.plan_id.placeholder': 'Chọn gói đăng ký',
  'common.modal.assign_order.cycle': 'Chọn chu kỳ',
  'common.modal.assign_order.cycle.placeholder': 'Chọn chu kỳ',
  'common.modal.assign_order.cycle.option.month_price': 'Hàng tháng',
  'common.modal.assign_order.cycle.option.quarter_price': 'Hàng quý',
  'common.modal.assign_order.cycle.option.half_year_price': 'Nửa năm',
  'common.modal.assign_order.cycle.option.year_price': 'Hàng năm',
  'common.modal.assign_order.cycle.option.two_year_price': 'Hai năm',
  'common.modal.assign_order.cycle.option.three_year_price': 'Ba năm',
  'common.modal.assign_order.cycle.option.onetime_price': 'Một lần',
  'common.modal.assign_order.cycle.option.reset_price': 'Gói đặt lại lưu lượng',
  'common.modal.assign_order.total_amount': 'Tổng số tiền',
  'common.modal.assign_order.total_amount.placeholder': 'Nhập số tiền cần thanh toán',
  'module.user.action.reset_secert.confirm.title': 'Đặt lại thông tin an toàn',
  'module.user.action.reset_secert.confirm.content': `Bạn có chắc muốn đặt lại thông tin an toàn cho {email} không?`,
  'module.user.action.reset_secert.message.success': 'Đặt lại thông tin an toàn thành công',
  'module.coupon.add_btn': 'Thêm mã giảm giá',
  'module.coupon.list.column.id': '#',
  'module.coupon.list.column.name': 'Tên mã giảm giá',
  'module.coupon.list.column.type': 'Loại',
  'module.coupon.list.column.type.amount': 'Số tiền',
  'module.coupon.list.column.type.proportion': 'Tỷ lệ',
  'module.coupon.list.column.code': 'Mã giảm giá',
  'module.coupon.list.column.limit_use': 'Lượt sử dụng còn lại',
  'module.coupon.list.column.limit_use.infinite': 'Vô hạn',
  'module.coupon.list.column.valid_period': 'Thời hạn hiệu lực',
  'module.coupon.list.column.action': 'Hoạt động',
  'module.coupon.list.column.action.edit': 'Chỉnh sửa',
  'module.coupon.list.column.action.drop': 'Xóa',
  'module.coupon.list.column.action.drop.message.success': 'Xóa thành công',
  'module.coupon.modal.edit_title': 'Chỉnh sửa mã giảm giá',
  'module.coupon.modal.create_title': 'Tạo mã giảm giá mới',
  'module.coupon.message.edit_success': 'Chỉnh sửa mã giảm giá thành công',
  'module.coupon.message.create_success': 'Tạo mã giảm giá mới thành công',
  'module.coupon.modal.name': 'Tên',
  'module.coupon.modal.name.placeholder': 'Nhập tên mã giảm giá',
  'module.coupon.modal.code': 'Mã giảm giá tùy chỉnh',
  'module.coupon.modal.code.placeholder': 'Mã giảm giá tùy chỉnh',
  'module.coupon.modal.type_value': 'Thông tin giảm giá',
  'module.coupon.modal.value.placeholder': 'Nhập giá trị',
  'module.coupon.modal.type.option.amount': 'Theo số tiền giảm',
  'module.coupon.modal.type.option.proportion': 'Theo tỷ lệ giảm',
  'module.coupon.modal.valid_period': 'Thời hạn giảm giá',
  'module.coupon.modal.limit_use': 'Số lần sử dụng tối đa',
  'module.coupon.modal.limit_use.placeholder': 'Giới hạn số lần sử dụng tối đa, hết lượt không thể sử dụng (để trống nếu không giới hạn)',
  'module.coupon.modal.limit_use_with_user': 'Số lần mỗi người dùng có thể sử dụng',
  'module.coupon.modal.limit_use_with_user.placeholder': 'Giới hạn số lần mỗi người dùng có thể sử dụng (để trống nếu không giới hạn)',
  'module.coupon.modal.limit_plan_ids': 'Chỉ áp dụng cho gói cụ thể',
  'module.coupon.modal.limit_plan_ids.placeholder': 'Giới hạn mã giảm giá chỉ áp dụng cho các gói cụ thể (để trống nếu không giới hạn)',
  'module.coupon.modal.generate_count': 'Số lượng tạo',
  'module.coupon.modal.generate_count.placeholder': 'Nhập số lượng để tạo mã giảm giá',
  'module.order.filter_btn': 'Bộ lọc',
  'module.order.add_btn': 'Thêm đơn hàng',
  'module.order.list.column.trade_no': '# Số đơn hàng',
  'module.order.list.column.type': 'Loại',
  'module.order.list.column.type.new_order': 'Đặt hàng mới',
  'module.order.list.column.type.renew': 'Gia hạn',
  'module.order.list.column.type.upgrade': 'Nâng cấp',
  'module.order.list.column.type.reset_price': 'Đặt lại',
  'module.order.list.column.plan_id': 'Gói đăng ký',
  'module.order.list.column.cycle': 'Kỳ hạn',
  'module.order.list.column.cycle.month_price': 'Hàng tháng',
  'module.order.list.column.cycle.quarter_price': 'Hàng quý',
  'module.order.list.column.cycle.half_year_price': 'Nửa năm',
  'module.order.list.column.cycle.year_price': 'Hàng năm',
  'module.order.list.column.cycle.two_year_price': 'Hai năm',
  'module.order.list.column.cycle.three_year_price': 'Ba năm',
  'module.order.list.column.cycle.onetime_price': 'Một lần',
  'module.order.list.column.cycle.reset_price': 'Đặt lại gói dữ liệu',
  'module.order.list.column.total_amount': 'Tổng số tiền thanh toán',
  'module.order.list.column.status': 'Trạng thái đơn hàng',
  'module.order.list.column.status.tip': 'Sau khi đánh dấu [Đã thanh toán], hệ thống sẽ mở và hoàn thành đơn hàng.',
  'module.order.list.column.status.unpaid': 'Chưa thanh toán',
  'module.order.list.column.status.pending': 'Đang xử lý',
  'module.order.list.column.status.cancelled': 'Đã hủy',
  'module.order.list.column.status.completed': 'Hoàn thành',
  'module.order.list.column.status.discounted': 'Đã giảm giá',
  'module.order.list.column.status.unpaid.mark': 'Đánh dấu là',
  'module.order.list.column.status.unpaid.mark.pending': 'Đã thanh toán',
  'module.order.list.column.status.unpaid.mark.cancelled': 'Đã hủy',
  'module.order.list.column.status.unpaid.mark.message.success': 'Đánh dấu trạng thái thành công',
  'module.order.list.column.commission_balance': 'Số tiền hoa hồng',
  'module.order.list.column.commission_status': 'Trạng thái hoa hồng',
  'module.order.list.column.commission_status.tip': 'Sau khi đánh dấu [Hiệu quả], hệ thống sẽ xử lý và chuyển tiền hoa hồng cho người dùng.',
  'module.order.list.column.commission_status.new': 'Chờ xác nhận',
  'module.order.list.column.commission_status.pending': 'Đang chuyển',
  'module.order.list.column.commission_status.valid': 'Đã chuyển',
  'module.order.list.column.commission_status.invalid': 'Đã từ chối',
  'module.order.list.column.commission_status.new.mark': 'Đánh dấu là',
  'module.order.list.column.commission_status.new.mark.valid': 'Hợp lệ',
  'module.order.list.column.commission_status.new.mark.invalid': 'Không hợp lệ',
  'module.order.list.column.commission_status.new.mark.message.success': 'Đánh dấu trạng thái hoa hồng thành công',
  'module.order.list.column.created_at': 'Thời gian tạo',
  'module.order.modal.detail.title': 'Thông tin đơn hàng',
  'module.order.modal.detail.email': 'Email',
  'module.order.modal.detail.trade_no': 'Số đơn hàng',
  'module.order.modal.detail.cycle': 'Kỳ hạn đơn hàng',
  'module.order.modal.detail.cycle.month_price': 'Hàng tháng',
  'module.order.modal.detail.cycle.quarter_price': 'Hàng quý',
  'module.order.modal.detail.cycle.half_year_price': 'Nửa năm',
  'module.order.modal.detail.cycle.year_price': 'Hàng năm',
  'module.order.modal.detail.cycle.two_year_price': 'Hai năm',
  'module.order.modal.detail.cycle.three_year_price': 'Ba năm',
  'module.order.modal.detail.cycle.onetime_price': 'Một lần',
  'module.order.modal.detail.cycle.reset_price': 'Đặt lại gói dữ liệu',
  'module.order.modal.detail.status': 'Trạng thái đơn hàng',
  'module.order.modal.detail.status.unpaid': 'Chưa thanh toán',
  'module.order.modal.detail.status.pending': 'Đang xử lý',
  'module.order.modal.detail.status.cancelled': 'Đã hủy',
  'module.order.modal.detail.status.completed': 'Hoàn thành',
  'module.order.modal.detail.status.discounted': 'Đã giảm giá',
  'module.order.modal.detail.plan_id': 'Kế hoạch đơn hàng',
  'module.order.modal.detail.created_at': 'Thời gian tạo',
  'module.order.modal.detail.updated_at': 'Thời gian cập nhật',
  'module.order.modal.detail.balance_amount': 'Số tiền thanh toán bằng số dư',
  'module.order.modal.detail.refund_amount': 'Số tiền hoàn trả',
  'module.order.modal.detail.discount_amount': 'Số tiền giảm giá',
  'module.order.modal.detail.total_amount': 'Tổng số tiền thanh toán',
  'module.order.modal.detail.callback_no': 'Số giao dịch cổng',
  'module.order.action.filter.name': 'Điều kiện',
  'module.order.action.filter.add_btn': 'Thêm điều kiện',
  'module.order.action.filter.filed_name': 'Tên trường',
  'module.order.action.filter.condition': 'Điều kiện',
  'module.order.action.filter.condition.like': 'Tương tự',
  'module.order.action.filter.value': 'Giá trị cần tìm',
  'module.order.action.filter.value.placeholder': 'Giá trị',
  'module.order.action.filter.drawer.ok_btn': 'Lọc',
  'module.order.action.filter.drawer.cancel_btn': 'Hủy',
  'module.order.action.filter.drawer.reset_btn': 'Đặt lại',
  'module.order.action.filter.drawer.title': 'Bộ lọc',
  'module.order.action.filter.filed_name.trade_no': 'Số đơn hàng',
  'module.order.action.filter.filed_name.status': 'Trạng thái đơn hàng',
  'module.order.action.filter.filed_name.commission_status': 'Trạng thái hoa hồng',
  'module.order.action.filter.filed_name.user_id': 'ID người dùng',
  'module.order.action.filter.filed_name.invite_user_id': 'ID người giới thiệu',
  'module.order.action.filter.value.select_placeholder': 'Chọn giá trị',
  'module.order.action.filter.value.status.option.unpaid': 'Chưa thanh toán',
  'module.order.action.filter.value.status.option.pending': 'Đang xử lý',
  'module.order.action.filter.value.status.option.cancelled': 'Đã hủy',
  'module.order.action.filter.value.status.option.completed': 'Hoàn thành',
  'module.order.action.filter.value.commission_status.option.new': 'Chờ xác nhận',
  'module.order.action.filter.value.commission_status.option.pending': 'Đang chuyển',
  'module.order.action.filter.value.commission_status.option.valid': 'Đã chuyển',
  'module.order.action.filter.value.commission_status.option.invalid': 'Đã từ chối',
}
